AWSTemplateFormatVersion: '2010-09-09'
Description: Launch a web server EC2 instance with Nginx on Ubuntu

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-020cba7c55df1f615
      SecurityGroups:
        - !Ref WebSG
      UserData:
        Fn::Base64: |
          #!/bin/bash
          apt update -y
          apt install nginx -y
          systemctl start nginx
          systemctl enable nginx
          echo "Hello World from Nginx on Ubuntu!" > /var/www/html/index.nginx-debian.html

  WebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0